steps:
#  step_2:
#    image: docker/whalesay
#    commands:
#      - sleep
#      - '2'
#  step_3:
#    image: docker/whalesay
#    commands:
#      - sleep
#      - '2'
#  step_4:
#    image: docker/whalesay
#    commands:
#      - sleep
#      - '2'
  step_3:
    image: docker/whalesay
    commands:
      - cowsay
      - hi
  step_4:
    image: docker/whalesay
    commands:
      - cowsay
      - hi
