version: '3'
services:
  server:
    build:
      args:
        - environment=dev
    volumes:
      - ../packages/server/:/app
  ui:
    build:
      args:
        - environment=dev
    volumes:
      - ../packages/ui/:/app
  mongo:
    ports:
      - 27017:27017