version: '3'
services:
  server:
    build:
      context: ../packages/server
    environment:
      CONTAINER_TIMEOUT: 10000 # 10 sec
    depends_on:
      - mongo
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
  ui:
    build:
      context: ../packages/ui
    ports:
      - 3000:3000
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db-data:/data/db

volumes:
  db-data:
